# -------------------------
# Ruff configuration
# -------------------------
target-version = "py310"
line-length = 100
indent-width = 4

# Formatting settings (Ruff replaces Black)
[format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true
skip-magic-trailing-comma = false

# Linting rules and exclusions
[lint]
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort-style imports
    "UP",   # pyupgrade (modern syntax)
    "B",    # bugbear (common mistakes)
    "C4",   # comprehensions
    "RUF",  # Ruff-specific rules
]

ignore = [
    "E501",  # line length handled by formatter
    "B008",  # function call i
]